runtime: python310
entrypoint: gunicorn -b :$PORT webApp:app

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 20

env_variables:
  OPENAI_API_KEY: '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'
  BUCKET_NAME: 'catboxv1'

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /(.*)
  static_files: dist/\1
  upload: dist/(.*)

